version: '3.1'
services:
  feature_db:
    image: mariadb
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "ninja55"
      MYSQL_DATABASE: "feature"
      MYSQL_USER: "feature"
      MYSQL_PASSWORD: "feature123"
    ports:
      - 33060:3306
volumes:
    db_data: